-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 17-04-2024 a las 02:41:53
-- Versión del servidor: 10.4.32-MariaDB
-- Versión de PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `comandos`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `linux_commands`
--

CREATE TABLE `linux_commands` (
  `id` int(11) NOT NULL,
  `command` text NOT NULL,
  `description` text NOT NULL,
  `ayuda` varchar(255) NOT NULL,
  `imagen` varchar(255) NOT NULL,
  `ejemplo` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `linux_commands`
--

INSERT INTO `linux_commands` (`id`, `command`, `description`, `ayuda`, `imagen`, `ejemplo`) VALUES
(1, 'cat', 'Es un comando utilizado para concatenar archivos y mostrar su contenido en la salida estándar (generalmente la pantalla). También se utiliza para crear nuevos archivos, concatenando varios archivos juntos. Por ejemplo, cat archivo1.txt archivo2.txt > nuevo_archivo.txt concatenaría el contenido de archivo1.txt y archivo2.txt en nuevo_archivo.txt.', 'https://www.hostinger.co/tutoriales/comando-cat-linux', 'https://i.ibb.co/54KJ6B0/Cat.png', '$ cat archivo1.txt\n$ cat archivo1.txt archivo2.txt\n$ cat archivo1.txt archivo2.txt > nuevo_archivo.txt\n$ cat *.txt\n$ cat archivo.txt | grep \"patrón\"\n$ cat archivo.txt | less\n$ cat archivo.txt | head -n 10\n$ cat archivo.txt | tail -n 10\n$ cat archivo.txt | sort\n$ cat archivo.txt | uniq\n$ cat archivo.txt | wc -l\n$ cat archivo.txt | sed \'s/palabra/reemplazo/g\'\n$ cat archivo.txt | awk \'{print $2}\'\n$ cat archivo.txt | cut -d\',\' -f1\n$ cat archivo.txt | tr \'[:lower:]\' \'[:upper:]\''),
(2, 'uname', 'Este comando se utiliza para mostrar información sobre el sistema operativo en uso. Puede mostrar detalles como el nombre del sistema operativo, la versión del kernel, el tipo de máquina, entre otros. Por ejemplo, uname -a mostrará toda la información disponible sobre el sistema.', 'https://man.cx/uname(1)/es', 'https://i.ibb.co/3NKXGR6/uname.png', '$ uname -s\n$ uname -r\n$ uname -m\n$ uname -v\n$ uname -p\n$ uname -o\n$ uname -n\n$ uname -a\n$ uname -i\n$ uname -X\n$ uname -l\n$ uname -c\n$ uname -u\n$ uname -t\n$ uname -N'),
(3, 'find', 'El comando find se utiliza para buscar archivos y directorios en un sistema de archivos. Puedes buscar archivos por nombre, tamaño, fecha de modificación, permisos, y otros criterios. Por ejemplo, find /home -name ', 'https://www.gnu.org/software/findutils/', 'https://i.ibb.co/RCNJcbf/find.png', '$ find / -name \"*.txt\"\n$ find . -type f -size +10M\n$ find /home/user -user username\n$ find /var/log -name \"*.log\"\n$ find /etc -type d -name \"conf\"\n$ find /usr/bin -executable\n$ find /usr/local/bin -mtime -7\n$ find /var -type f -size +100M\n$ find /tmp -type f -empty\n$ find /home -type f -name \"*.mp3\"\n$ find /var/log -mtime -1\n$ find /home/user -maxdepth 1 -type d\n$ find /var/log -name \"*.log\" -exec cp {} /backup/ \\;\n$ find /home -type f -name \"*.txt\" -exec grep -H \"patrón\" {} \\;\n$ find /var/log -type f -name \"*.log\" -exec tail -n 10 {} \\;'),
(4, 'dmidecode', 'Este comando proporciona información sobre el hardware del sistema, utilizando la tabla de datos de gestión de dispositivos (DMI) en el sistema. Puede mostrar detalles sobre la BIOS, la CPU, la memoria, los dispositivos de entrada/salida, entre otros. Por ejemplo, sudo dmidecode -t memory mostrará información sobre la memoria del sistema.', 'https://linux.die.net/man/8/dmidecode', 'https://i.ibb.co/KLy48JT/dmidecode.png', '$ sudo dmidecode --type memory\r\n$ sudo dmidecode --type bios\r\n$ sudo dmidecode --type system\r\n$ sudo dmidecode --type processor\r\n$ sudo dmidecode --type baseboard\r\n$ sudo dmidecode --type memory | grep -i size\r\n$ sudo dmidecode --type bios | grep -i version\r\n$ sudo dmidecode --type processor | grep -i version\r\n$ sudo dmidecode --type system | grep -i manufacturer\r\n$ sudo dmidecode --type baseboard | grep -i manufacturer\r\n$ sudo dmidecode --type system | grep -i uuid\r\n$ sudo dmidecode --type memory | grep -i part\r\n$ sudo dmidecode --type bios | grep -i release\r\n$ sudo dmidecode --type system | grep -i serial'),
(5, 'date', 'El comando date muestra la fecha y hora actual del sistema. También se puede utilizar para establecer la fecha y hora del sistema. Por ejemplo, date mostrará la fecha y hora actuales, mientras que date MMDDhhmm establecerá la fecha y hora en el formato MMDDhhmm.', 'https://www.gnu.org/software/coreutils/manual/html_node/date-invocation.html', 'https://i.ibb.co/6s7Z4pS/date.png', '$ date\r\n$ date +\"%Y-%m-%d %H:%M:%S\"\r\n$ date -d \"next Friday\"\r\n$ date -u\r\n$ date -R\r\n$ date -d \"3 days ago\" +\"%Y-%m-%d\"\r\n$ date -d \"next Friday\" +\"%Y-%m-%d\"\r\n$ date -d \"-1 year\" +\"%Y-%m-%d\"\r\n$ date -d \"tomorrow\" +\"%Y-%m-%d\"\r\n$ date -d \"next month\" +\"%Y-%m-%d\"\r\n$ date -d \"last week\" +\"%Y-%m-%d\"\r\n$ date -d \"next year\" +\"%Y-%m-%d\"\r\n$ date -d \"yesterday\" +\"%Y-%m-%d\"\r\n$ date -d \"1 month ago\" +\"%Y-%m-%d\"\r\n$ date -d \"2 weeks ago\" +\"%Y-%m-%d\"'),
(6, 'hdparm', 'Este comando se utiliza para interactuar con y controlar los dispositivos de almacenamiento ATA. Puede mostrar información sobre los discos duros y unidades de estado sólido (SSD), así como ajustar configuraciones como la velocidad de transferencia y el modo de energía. Por ejemplo, hdparm -I /dev/sda mostrará información detallada sobre el disco /dev/sda.', 'https://man7.org/linux/man-pages/man8/hdparm.8.html', 'https://i.ibb.co/Fhc7WGs/hdparm.png', '$ sudo hdparm -I /dev/sda\r\n$ sudo hdparm -S 60 /dev/sda\r\n$ sudo hdparm -tT /dev/sda\r\n$ sudo hdparm -y /dev/sda\r\n$ sudo hdparm -B 255 /dev/sda\r\n$ sudo hdparm -W 1 /dev/sda\r\n$ sudo hdparm -a 64 /dev/sda\r\n$ sudo hdparm -m 16 /dev/sda\r\n$ sudo hdparm -u 1 /dev/sda\r\n$ sudo hdparm -c 1 /dev/sda\r\n$ sudo hdparm -d 1 /dev/sda\r\n$ sudo hdparm -p 1 /dev/sda\r\n$ sudo hdparm -X 69 /dev/sda\r\n$ sudo hdparm -K 1 /dev/sda\r\n$ sudo hdparm -M 128 /dev/sda'),
(7, 'lspci', 'Se utiliza para mostrar información sobre los dispositivos PCI conectados al sistema. Proporciona detalles sobre los dispositivos de hardware, como la tarjeta gráfica, la tarjeta de red, etc. Por ejemplo, lspci mostrará una lista de todos los dispositivos PCI en el sistema.', 'https://man7.org/linux/man-pages/man8/lspci.8.html', 'https://i.ibb.co/f08ZS1W/Ispci.png', '$ lspci\r\n$ lspci -v\r\n$ lspci -nn\r\n$ lspci -k\r\n$ lspci -m\r\n$ lspci -t\r\n$ lspci -x\r\n$ lspci -s 00:00.0\r\n$ lspci -b\r\n$ lspci -D\r\n$ lspci -H 1\r\n$ lspci -i\r\n$ lspci -n\r\n$ lspci -vmm\r\n$ lspci -xxx'),
(8, 'which', 'Este comando se utiliza para mostrar la ruta completa de los ejecutables que se están utilizando en el sistema. Si hay múltiples ejecutables con el mismo nombre, which mostrará la ruta del primero que encuentre en el PATH. Por ejemplo, which ls mostrará la ruta del comando ls.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-which-de-linux', 'https://i.ibb.co/mz7GqXc/which.png', '$ which ls\r\n$ which nano\r\n$ which python\r\n$ which gcc\r\n$ which java\r\n$ which ffmpeg\r\n$ which grep\r\n$ which wget\r\n$ which curl\r\n$ which tar\r\n$ which find\r\n$ which cat\r\n$ which awk\r\n$ which sed\r\n$ which sort'),
(9, 'ls', 'Es un comando utilizado para listar archivos y directorios en un sistema de archivos. Puede mostrar detalles como el nombre, tamaño, permisos y fecha de modificación de los archivos. Por ejemplo, ls -l mostrará una lista detallada de archivos y directorios en el directorio actual.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-ls-de-linux', 'https://i.ibb.co/jZ2BWxz/ls.png', '$ ls -l\r\n$ ls -a\r\n$ ls -lh\r\n$ ls -R\r\n$ ls -lt\r\n$ ls -i\r\n$ ls -d\r\n$ ls -S\r\n$ ls -h\r\n$ ls -g\r\n$ ls -r\r\n$ ls -1\r\n$ ls -C\r\n$ ls -F\r\n$ ls -t'),
(10, 'ps', 'Este comando se utiliza para mostrar información sobre los procesos en ejecución en el sistema. Puede mostrar detalles como el ID del proceso (PID), el uso de la CPU, la memoria, el estado del proceso, entre otros. Por ejemplo, ps aux mostrará una lista detallada de todos los procesos en ejecución.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-ps-de-linux', 'https://i.ibb.co/QjZ3WsP/ps.png', '$ ps\r\n$ ps -ef\r\n$ ps aux\r\n$ ps -e | grep \"patrón\"\r\n$ ps -u username\r\n$ ps -f\r\n$ ps -l\r\n$ ps -H\r\n$ ps -N\r\n$ ps -o pid,ppid,cmd\r\n$ ps -p PID\r\n$ ps -t\r\n$ ps -x\r\n$ ps -Z'),
(11, 'du', 'Se utiliza para mostrar el uso del espacio en disco de archivos y directorios en el sistema. Puede mostrar el tamaño total de un directorio y sus subdirectorios, así como el tamaño de archivos individuales. Por ejemplo, du -sh /carpeta mostrará el tamaño total de la carpeta /carpeta.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-du-de-linux', 'https://i.ibb.co/H4FttjS/du.png', '$ du -sh /ruta/al/directorio\r\n$ du -h\r\n$ du -sh *\r\n$ du -a\r\n$ du -ch\r\n$ du -c\r\n$ du -d 1\r\n$ du -b\r\n$ du -L\r\n$ du -m\r\n$ du -S\r\n$ du -t\r\n$ du -x\r\n$ du -z\r\n$ du --exclude=\"*.txt\"'),
(12, 'top', 'Es un comando utilizado para mostrar una lista en tiempo real de los procesos que están utilizando la mayor cantidad de recursos del sistema, como CPU y memoria. Es útil para monitorear el rendimiento del sistema y detectar procesos que consumen muchos recursos. Por ejemplo, top mostrará una lista dinámica de los procesos en ejecución.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-top-de-linux', 'https://i.ibb.co/6g4d6zM/top.png', '$ top\r\n$ top -u username\r\n$ top -n 1\r\n$ top -p PID\r\n$ top -i\r\n$ top -b\r\n$ top -c\r\n$ top -d\r\n$ top -e\r\n$ top -h\r\n$ top -l\r\n$ top -m\r\n$ top -o\r\n$ top -R\r\n$ top -s'),
(13, 'df', 'Se utiliza para mostrar el espacio disponible y utilizado en los sistemas de archivos montados en el sistema. Puede mostrar detalles como el tamaño total, el espacio utilizado y el espacio libre en cada sistema de archivos. Por ejemplo, df -h mostrará el espacio en disco disponible y utilizado en un formato legible para humanos.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-df-de-linux', 'https://i.ibb.co/SPxjQcH/df.png', '$ df -h\r\n$ df -T\r\n$ df -i\r\n$ df -k\r\n$ df -a\r\n$ df -B 1\r\n$ df -hT\r\n$ df -m\r\n$ df -P\r\n$ df -x\r\n$ df --sync\r\n$ df --total\r\n$ df --help\r\n$ df --version\r\n$ df --sync'),
(14, 'tail', 'Este comando se utiliza para mostrar las últimas líneas de un archivo de texto. Es útil para monitorear archivos de registro en tiempo real. Por ejemplo, tail -n 10 archivo.txt mostrará las últimas 10 líneas del archivo archivo.txt.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-tail-de-linux', 'https://i.ibb.co/wN31Kz8/tail.png', '$ tail archivo.log\r\n$ tail -n 10 archivo.log\r\n$ tail -f archivo.log\r\n$ tail -F archivo.log\r\n$ tail -r archivo.log\r\n$ tail -c 100 archivo.log\r\n$ tail -q archivo.log\r\n$ tail -v archivo.log\r\n$ tail -z archivo.log\r\n$ tail -s 10 archivo.log\r\n$ tail -S archivo.log\r\n$ tail -N archivo.log\r\n$ tail -m archivo.log\r\n$ tail -q archivo.log\r\n$ tail -r archivo.log'),
(15, 'who', 'Muestra una lista de usuarios que están actualmente conectados al sistema. Puede mostrar detalles como el nombre de usuario, la terminal desde la que están conectados y la hora de inicio de sesión. Por ejemplo, who mostrará una lista de usuarios conectados.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-who-de-linux', 'https://i.ibb.co/k1N0Q7s/who.png', '$ who\r\n$ who -a\r\n$ who -b\r\n$ who -d\r\n$ who -m\r\n$ who -q\r\n$ who -r\r\n$ who -s\r\n$ who -t\r\n$ who -u\r\n$ who -l\r\n$ who -T\r\n$ who -p\r\n$ who -v\r\n$ who -w'),
(16, 'alias', 'Este comando se utiliza para asignar un alias o un nombre corto a un comando más largo. Es útil para crear abreviaturas para comandos frecuentemente utilizados o para cambiar el comportamiento predeterminado de un comando. Por ejemplo, alias ll=\'ls -l\' asignará el alias ll al comando ls -l.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-alias-de-linux', 'https://i.ibb.co/2jdQwH4/alias.png', '$ alias ll=\'ls -l\'\r\n$ alias cls=\'clear\'\r\n$ alias ..=\'cd ..\'\r\n$ alias c=\'clear\'\r\n$ alias h=\'history\'\r\n$ alias grep=\'grep --color=auto\'\r\n$ alias df=\'df -h\'\r\n$ alias du=\'du -h\'\r\n$ alias mkdir=\'mkdir -p\'\r\n$ alias ps=\'ps aux\'\r\n$ alias grep=\'grep --color=auto\'\r\n$ alias cp=\'cp -i\'\r\n$ alias mv=\'mv -i\'\r\n$ alias rm=\'rm -i\'\r\n$ alias sudo=\'sudo \''),
(17, 'wget', 'Se utiliza para descargar archivos desde Internet utilizando el protocolo HTTP, HTTPS o FTP. Puede descargar archivos individuales o páginas web completas. Por ejemplo, wget http://ejemplo.com/archivo.txt descargará el archivo archivo.txt desde el sitio web ejemplo.com.', 'https://www.gnu.org/software/wget/manual/wget.html', 'https://i.ibb.co/9T4NhkT/wget.png', '$ wget http://example.com/archivo.txt\r\n$ wget -O archivo_destino.txt http://example.com/archivo.txt\r\n$ wget -r -np http://example.com/directorio/\r\n$ wget --ftp-user=usuario --ftp-password=password ftp://example.com/archivo.txt\r\n$ wget -c http://example.com/gran_archivo.zip\r\n$ wget -i urls.txt\r\n$ wget --limit-rate=200k http://example.com/archivo.txt\r\n$ wget --no-check-certificate https://example.com/archivo.txt\r\n$ wget -T 10 http://example.com/archivo.txt\r\n$ wget --spider http://example.com/archivo.txt\r\n$ wget --mirror -p --convert-links -P ./local_dir http://example.com\r\n$ wget --continue http://example.com/archivo.txt\r\n$ wget --user=usuario --password=password http://example.com/archivo.txt\r\n$ wget --content-disposition http://example.com/archivo_con_disposicion.txt\r\n$ wget -U \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36\" http://example.com/'),
(18, 'kill', 'Se utiliza para enviar señales a procesos en ejecución para detenerlos o modificar su comportamiento. Puede enviar señales como SIGTERM para terminar un proceso de manera segura o SIGKILL para terminarlo inmediatamente. Por ejemplo, kill -9 PID terminará el proceso con el ID de proceso (PID) especificado.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-kill-de-linux', 'https://i.ibb.co/nfV3WYS/kill.png', '$ kill PID\r\n$ kill -9 PID\r\n$ killall proceso\r\n$ pkill proceso\r\n$ pkill -f \"nombre_proceso\"\r\n$ kill -15 PID\r\n$ kill -l\r\n$ kill -HUP PID\r\n$ kill -INT PID\r\n$ kill -TERM PID\r\n$ kill -STOP PID\r\n$ kill -CONT PID\r\n$ kill -KILL PID\r\n$ kill -USR1 PID\r\n$ kill -USR2 PID'),
(19, 'lsof', 'Este comando se utiliza para listar los archivos que están abiertos por los procesos en el sistema. Puede mostrar detalles como el nombre del archivo, el proceso que lo tiene abierto y el identificador del descriptor de archivo. Por ejemplo, lsof /ruta/al/archivo mostrará los procesos que tienen abierto el archivo especificado.', 'https://man7.org/linux/man-pages/man8/lsof.8.html', 'https://i.ibb.co/0X8frPD/lsof.png', '$ lsof -i :80\r\n$ lsof -u usuario\r\n$ lsof -c proceso\r\n$ lsof /ruta/al/archivo\r\n$ lsof -i TCP:puerto\r\n$ lsof -i udp:puerto\r\n$ lsof -i :22\r\n$ lsof -p PID\r\n$ lsof -t /ruta/al/archivo\r\n$ lsof -iTCP:80\r\n$ lsof -iTCP -sTCP:LISTEN\r\n$ lsof -u $(whoami)\r\n$ lsof -i -n -P\r\n$ lsof -iTCP@hostname:port\r\n$ lsof -i@ip:port'),
(20, 'whois', 'Se utiliza para obtener información sobre un nombre de dominio, como el registrante, el servidor de nombres, la fecha de registro, etc. Por ejemplo, whois ejemplo.com mostrará información sobre el dominio ejemplo.com.', 'https://ayuda.hostalia.com/hc/es/article_attachments/360009539597', 'https://i.ibb.co/xgRLLPX/whois.png', '$ whois example.com\r\n$ whois -h whois.arin.net 8.8.8.8\r\n$ whois -H example.com\r\n$ whois -T domain example.com\r\n$ whois -r example.com\r\n$ whois -a example.com\r\n$ whois -i origin example.com\r\n$ whois -i admin-c example.com\r\n$ whois -i tech-c example.com\r\n$ whois -i bill-c example.com\r\n$ whois -i nic-hdl example.com\r\n$ whois -i org example.com\r\n$ whois -i range example.com\r\n$ whois -i netname example.com\r\n$ whois -i descr example.com'),
(21, 'nslookup', '$ nslookup example.com\r\n$ nslookup -type=mx example.com\r\n$ nslookup -type=ns example.com\r\n$ nslookup -type=txt example.com\r\n$ nslookup -type=any example.com\r\n$ nslookup -debug example.com\r\n$ nslookup -query=ns example.com\r\n$ nslookup -query=mx example.com\r\n$ nslookup -query=soa example.com\r\n$ nslookup -query=ptr 192.168.1.1\r\n$ nslookup -query=any example.com\r\n$ nslookup -query=ns example.com\r\n$ nslookup -query=txt example.com\r\n$ nslookup -query=ptr 8.8.8.8\r\n$ nslookup -query=mx example.com', 'https://learn.microsoft.com/es-es/windows-server/administration/windows-commands/nslookup', 'https://i.ibb.co/CtQbCWh/nslookup.png', '$ nslookup example.com\r\n$ nslookup -type=mx example.com\r\n$ nslookup -type=ns example.com\r\n$ nslookup -type=txt example.com\r\n$ nslookup -type=any example.com\r\n$ nslookup -debug example.com\r\n$ nslookup -query=ns example.com\r\n$ nslookup -query=mx example.com\r\n$ nslookup -query=soa example.com\r\n$ nslookup -query=ptr 192.168.1.1\r\n$ nslookup -query=any example.com\r\n$ nslookup -query=ns example.com\r\n$ nslookup -query=txt example.com\r\n$ nslookup -query=ptr 8.8.8.8\r\n$ nslookup -query=mx example.com'),
(22, 'hostname', 'Este comando se utiliza para mostrar o configurar el nombre del host de la máquina. El nombre de host identifica de manera única a un sistema en una red. Cuando se ejecuta sin argumentos, simplemente muestra el nombre de host actual de la máquina. También se puede utilizar para cambiar el nombre del host ejecutándolo con el nuevo nombre como argumento. Por ejemplo, hostname mostrará el nombre de host actual, mientras que hostname nuevo_nombre cambiará el nombre del host a \"nuevo_nombre\".', 'https://www.gnu.org/software/coreutils/manual/html_node/hostname-invocation.html', 'https://i.ibb.co/FhKwCjJ/hostname.png', '$ hostname\r\n$ hostname -i\r\n$ hostname -f\r\n$ hostname -d\r\n$ hostname -y\r\n$ hostname -I\r\n$ hostname -s\r\n$ hostname -v\r\n$ hostname -a\r\n$ hostname -b\r\n$ hostname -c\r\n$ hostname -e\r\n$ hostname -l\r\n$ hostname -m\r\n$ hostname -o'),
(23, 'host', 'El comando host se utiliza para realizar consultas DNS (Sistema de Nombres de Dominio). Permite traducir nombres de dominio a direcciones IP y viceversa. Puede utilizarse para realizar consultas de resolución de nombres para obtener información sobre un nombre de host en particular o una dirección IP. Por ejemplo, host ejemplo.com mostrará la dirección IP asociada con el dominio ejemplo.com.', 'https://www.ochobitshacenunbyte.com/2022/06/17/comando-host-en-linux-con-ejemplos/#:~:text=El%20comando%20host%20es%20una,opciones%20de%20l%C3%ADnea%20de%20comandos.', 'https://i.ibb.co/GMnVD5b/host.png', '$ host example.com\n$ host -a example.com\n$ host -t A example.com\n$ host -t AAAA example.com\n$ host -t NS example.com\n$ host -t CNAME example.com\n$ host -t MX example.com\n$ host -t TXT example.com\n$ host -t PTR 8.8.8.8\n$ host -t SOA example.com\n$ host -t SRV _service._proto.name\n$ host -l domain.com\n$ host -v example.com\n$ host -W 2 example.com\n$ host -6 example.com'),
(24, 'tar', 'Es una herramienta de línea de comandos utilizada para archivar y comprimir archivos y directorios en un solo archivo. Es comúnmente usado en sistemas Unix y Linux. El nombre \"tar\" proviene de \"Tape ARchive\", aunque hoy en día es comúnmente utilizado para crear archivos comprimidos incluso sin cintas. Se puede utilizar con varias opciones para comprimir, descomprimir, listar y manipular archivos de respaldo. Por ejemplo, tar -czvf archivo.tar.gz carpeta comprimirá y empaquetará la carpeta \"carpeta\" en un archivo llamado \"archivo.tar.gz\".', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-tar-de-linux', 'https://i.ibb.co/4Kgc9ng/tar.png', '$ tar -cvf archivo.tar carpeta\r\n$ tar -xvf archivo.tar\r\n$ tar -tvf archivo.tar\r\n$ tar -zcvf archivo.tar.gz carpeta\r\n$ tar -zxvf archivo.tar.gz\r\n$ tar -ztvf archivo.tar.gz\r\n$ tar -cvf archivo.tar --exclude=\'*.txt\' carpeta\r\n$ tar -xvf archivo.tar -C /directorio/destino\r\n$ tar -rvf archivo.tar archivo_nuevo\r\n$ tar -uvf archivo.tar archivo_modificado\r\n$ tar -xvf archivo.tar --strip-components=1\r\n$ tar -cvf archivo.tar --files-from=lista_archivos.txt\r\n$ tar -xvf archivo.tar -C /directorio/destino --strip-components=1\r\n$ tar -cvf archivo.tar carpeta1 carpeta2\r\n$ tar -xvf archivo.tar -C /directorio/destino --wildcards \"*.txt\"'),
(25, 'shutdown', 'Este comando se utiliza para apagar o reiniciar el sistema de forma controlada. Permite al usuario especificar el tiempo en el que se llevará a cabo la acción de apagado o reinicio, así como enviar un mensaje a los usuarios conectados notificándoles sobre el apagado o reinicio. Por ejemplo, shutdown -h now apagará el sistema inmediatamente.', 'https://www.ionos.es/digitalguide/servidores/configuracion/comandos-shutdown-de-linux/', 'https://i.ibb.co/CP94YLg/shutdown.png', '$ shutdown\r\n$ shutdown -h now\r\n$ shutdown -r 10\r\n$ shutdown -h 18:00\r\n$ shutdown -c\r\n$ shutdown -k now\r\n$ shutdown -P now\r\n$ shutdown -r +5\r\n$ shutdown -h +30\r\n$ shutdown -c\r\n$ shutdown -k now\r\n$ shutdown -P now\r\n$ shutdown -r +5\r\n$ shutdown -h +30\r\n$ shutdown -c'),
(26, 'halt', 'Es un comando que detiene el sistema de forma inmediata. Es similar al comando shutdown -h now, pero no ofrece la opción de programar el apagado o reinicio. Simplemente detiene todas las actividades del sistema y lo apaga de inmediato.', 'https://man.freebsd.org/cgi/man.cgi?halt(8)', 'https://i.ibb.co/rHxcKMp/halt.png', '$ halt\n$ halt -p\n$ halt -f\n$ halt -i\n$ halt -d\n$ halt -k\n$ halt -q\n$ halt -r\n$ halt -H\n$ halt -D\n$ halt -K\n$ halt -F\n$ halt -t\n$ halt -n\n$ halt -h'),
(27, 'reboot', 'Este comando reinicia el sistema de forma controlada. Es similar al comando shutdown -r now, pero ofrece una forma más directa de reiniciar el sistema sin necesidad de especificar opciones adicionales.', 'https://geekflare.com/es/reboot-shutdown-linux-commands/', 'https://i.ibb.co/RcyqbPY/reboot.png', '$ reboot\r\n$ reboot -p\r\n$ reboot -f\r\n$ reboot -i\r\n$ reboot -d\r\n$ reboot -k\r\n$ reboot -q\r\n$ reboot -r\r\n$ reboot -H\r\n$ reboot -D\r\n$ reboot -K\r\n$ reboot -F\r\n$ reboot -t\r\n$ reboot -n\r\n$ reboot -h'),
(28, 'logout', 'Se utiliza para cerrar la sesión de usuario actual en la terminal o el shell en uso. Es útil cuando se trabaja en entornos de línea de comandos y se desea cerrar la sesión sin apagar o reiniciar el sistema. Una vez ejecutado, el usuario es devuelto al estado de inicio de sesión para ingresar las credenciales nuevamente o cerrar la terminal si así lo desea.', 'https://soloconlinux.org.es/comandos-linux-apagar-cerrar/#:~:text=%E2%96%B6%20shutdown%20%2Dr%20now%20%E2%86%92,%E2%96%B6%20logout%20%E2%86%92%20cerrar%20sesi%C3%B3n.', 'https://i.ibb.co/8643JHM/logout.png', '$ logout\r\n'),
(29, 'exit', 'Este comando se utiliza para salir de la sesión actual de la terminal o el shell. Si se ejecuta en una ventana de terminal, cerrará esa ventana. Si se ejecuta en un script, terminará la ejecución del script. También puede ser utilizado en scripts para salir de bucles o condicionales. En resumen, se utiliza para salir de un contexto de ejecución.', 'https://soloconlinux.org.es/comandos-linux-apagar-cerrar/#:~:text=%E2%96%B6%20shutdown%20%2Dr%20now%20%E2%86%92,%E2%96%B6%20logout%20%E2%86%92%20cerrar%20sesi%C3%B3n.', 'https://i.ibb.co/XWqDYMq/exit.png', '$ exit'),
(30, 'vi', 'Es un editor de texto en modo texto utilizado en sistemas Unix y Linux. Vi es un editor modal, lo que significa que tiene modos de operación distintos, como el modo de inserción para editar texto y el modo de comando para realizar acciones como guardar el archivo o buscar texto. Es muy potente y eficiente una vez que se domina, aunque su curva de aprendizaje puede ser empinada para los usuarios nuevos.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-vim-del-editor-de-linux', 'https://i.ibb.co/zx8WX05/vim.png', '$ vi archivo.txt'),
(31, 'nano', 'Es un editor de texto simple y fácil de usar en línea de comandos. Es una alternativa más amigable para aquellos que no están familiarizados con vi o prefieren una interfaz más intuitiva. Nano proporciona atajos de teclado simples para realizar operaciones como guardar archivos, buscar y reemplazar texto, y otras funciones de edición de texto básicas. Es especialmente popular entre los usuarios principiantes o aquellos que necesitan editar rápidamente archivos de texto en la terminal.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-nano-del-editor-de-linux', 'https://i.ibb.co/L5LHFbH/nano.png', '$ nano archivo.txt'),
(32, 'man', 'El comando man es una herramienta de línea de comandos que se utiliza para acceder a las páginas de manual en sistemas Unix y Linux. Estas páginas de manual son documentos detallados que proporcionan información sobre diversos aspectos del sistema, incluyendo comandos, programas, funciones del sistema y archivos de configuración.\r\n\r\nCuando se utiliza el comando man, se proporciona el nombre del comando o función que se desea consultar, y man muestra la página de manual correspondiente en el terminal. Por ejemplo, para ver la página de manual del comando ls, se escribe man ls y se presiona Enter.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-man-de-linux', 'https://i.ibb.co/Vpj9hgj/man.png', 'man ls\r\nman man\r\nman -k network\r\nman -k .\r\nman 3 printf\r\nman -P cat ls\r\nman -P \'/usr/bin/less -p \"word\"\' command\r\nman -P \'less -+F\' command\r\nman -T txt command\r\nman -f command\r\nman /path/to/file\r\nman 2 open\r\nman -D command\r\nman -l command\r\nman -f command'),
(33, 'cd', 'El comando cd, abreviatura de \"change directory\" (cambiar directorio), es una herramienta fundamental en sistemas operativos Unix y Linux, así como en la interfaz de línea de comandos (CLI) de otros sistemas. Su función principal es cambiar el directorio actual en el que se encuentra el usuario en la estructura de archivos del sistema.\r\n\r\nPara utilizar el comando cd, se proporciona como argumento el nombre del directorio al que se desea mover. Por ejemplo, para cambiar al directorio \"Documentos\", se escribe cd Documentos y se presiona Enter. Si el directorio especificado existe dentro del directorio actual, el comando cd cambiará al nuevo directorio.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-cd-de-linux', 'https://i.ibb.co/SPyPbg2/cd.png', 'cd directorio\r\ncd ..\r\ncd /\r\ncd ~\r\ncd -\r\ncd ~/Documentos\r\ncd /usr/local/bin\r\ncd ../../\r\ncd ../../../\r\ncd /var/log\r\ncd /etc/\r\ncd /home/usuario/archivos\r\ncd ../carpeta\r\ncd ~/Desktop\r\ncd /ruta/al/directorio'),
(34, 'pwd', 'El comando pwd, abreviatura de ', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-pwd-de-linux', 'https://i.ibb.co/jvgpfhb/pwd.png', 'pw show user <nombre_de_usuario>'),
(35, 'mkdir', 'El comando mkdir, abreviatura de \"make directory\" (crear directorio), es una herramienta utilizada en sistemas Unix, Linux y otros sistemas operativos para crear nuevos directorios en el sistema de archivos.\r\n\r\nCuando se utiliza el comando mkdir, se proporciona como argumento el nombre del directorio que se desea crear. Por ejemplo, para crear un nuevo directorio llamado \"nuevo_directorio\", se escribe mkdir nuevo_directorio y se presiona Enter. Si el directorio especificado no existe en la ubicación actual del usuario, mkdir creará el nuevo directorio.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-mkdir-de-linux', 'https://i.ibb.co/FshdSQ6/mkdir.png', 'mkdir carpeta_nueva\r\nmkdir -p directorio1/directorio2\r\nmkdir -m 755 carpeta_permisos\r\nmkdir -v carpeta_con_output\r\nmkdir -p directorio1/{subdir1,subdir2}\r\nmkdir -p directorio/{subdir1,subdir2}/{subdir3,subdir4}\r\nmkdir -p directorio/{subdir1,subdir2}/{subdir3,subdir4}/{subdir5,subdir6}\r\nmkdir --mode=777 carpeta_con_permisos\r\nmkdir -p carpeta_existente/nueva_carpeta\r\nmkdir -p /ruta/a/directorio/nuevo\r\nmkdir -v directorio_con_output\r\nmkdir -m 700 carpeta_con_permisos\r\nmkdir -p directorio1/{subdir1,subdir2}/{subdir3,subdir4}/{subdir5,subdir6}\r\nmkdir -p directorio/{subdir1,subdir2}/{subdir3,subdir4}/{subdir5,subdir6}/{subdir7,subdir8}\r\nmkdir --verbose directorio_con_output'),
(36, 'rmdir', 'El comando rmdir, abreviatura de \"remove directory\" (eliminar directorio), se utiliza en sistemas Unix, Linux y otros sistemas operativos similares para eliminar directorios vacíos del sistema de archivos.\r\nPara utilizar el comando rmdir, se proporciona como argumento el nombre del directorio que se desea eliminar. Por ejemplo, para eliminar un directorio llamado \"directorio_vacio\", se escribe rmdir directorio_vacio y se presiona Enter. Es importante destacar que rmdir solo puede eliminar directorios que estén vacíos; si el directorio contiene archivos o subdirectorios, el comando mostrará un error.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-rmdir-de-linux', 'https://i.ibb.co/qm0ZQYm/rmdir.png', 'rmdir directorio_vacio\r\nrmdir -v directorio_vacio\r\nrmdir directorio1 directorio2\r\nrmdir -p directorio1/subdirectorio\r\nrmdir --ignore-fail-on-non-empty directorio_con_contenido\r\nrmdir -v directorio_con_output\r\nrmdir --verbose directorio_con_output\r\nrmdir -p directorio1/{subdir1,subdir2}\r\nrmdir -p directorio/{subdir1,subdir2}/{subdir3,subdir4}\r\nrmdir -p directorio/{subdir1,subdir2}/{subdir3,subdir4}/{subdir5,subdir6}\r\nrmdir --ignore-fail-on-non-empty directorio_no_vacio\r\nrmdir -v directorio_vacio\r\nrmdir -v directorio_vacio1 directorio_vacio2\r\nrmdir -p directorio1/{subdir1,subdir2}/{subdir3,subdir4}/{subdir5,subdir6}\r\nrmdir --ignore-fail-on-non-empty directorio_no_vacio'),
(37, 'mv', 'El comando mv, abreviatura de \"move\" (mover), es una herramienta de la línea de comandos en sistemas Unix, Linux y otros sistemas operativos similares que se utiliza para mover o renombrar archivos y directorios.\r\n\r\nPara utilizar el comando mv, se proporcionan dos argumentos: el primero es el nombre del archivo o directorio que se desea mover, y el segundo es la ubicación de destino donde se desea mover el archivo o directorio, o el nuevo nombre si se está renombrando. Por ejemplo:', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-mv-de-linux', 'https://i.ibb.co/g3B9smv/mv.png', 'mv archivo.txt nuevo_directorio/\r\nmv -v archivo.txt nuevo_directorio/\r\nmv archivo1.txt archivo2.txt\r\nmv -i archivo1.txt archivo2.txt\r\nmv -u archivo1.txt archivo2.txt\r\nmv directorio_viejo/ directorio_nuevo/\r\nmv -T directorio_viejo/ directorio_nuevo/\r\nmv -b archivo.txt directorio_backup/\r\nmv -f archivo.txt directorio_destino/\r\nmv -u archivo.txt directorio_destino/\r\nmv -t directorio_destino/ archivo1.txt archivo2.txt\r\nmv -i archivo1.txt archivo2.txt archivo3.txt directorio_destino/\r\nmv -u archivo1.txt archivo2.txt archivo3.txt directorio_destino/\r\nmv -v archivo* directorio_destino/\r\nmv -b archivo1.txt archivo2.txt archivo3.txt directorio_destino/'),
(38, 'clear', 'se utiliza para limpiar los comandos en la terminal, borra el texto de la pantalla o consola.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-clear-de-linux', 'https://i.ibb.co/2Nq4PTq/clear.png', 'clear: Es un comando estandar que se utiliza para borrar pantalla.'),
(39, 'echo', 'Es un comando para la impresión de un texto en pantalla. Es utilizado en las terminales de los sistemas operativos como Unix, GNU/Linux, o MS-DOS; dentro de pequeños programas llamados scripts; y en ciertos lenguajes de programación tales como PHP.', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-echo-de-linux', 'https://i.ibb.co/Qb41Gn0/echo.png', 'echo \"Hola, mundo!\"\r\n'),
(40, 'cp', 'El comando cp copia un archivo a otro. También puede copiar varios ficheros en un directorio determinado. ', 'https://www.freecodecamp.org/espanol/news/comandos-de-linux/#el-comando-cp-de-linux', 'https://i.ibb.co/NpYXLWx/cp.png', 'cp archivo.txt directorio/\r\ncp archivo1.txt archivo2.txt directorio/\r\ncp -r directorio_origen/ directorio_destino/\r\ncp archivo.txt nuevo_nombre.txt\r\n'),
(41, 'rm', 'El mandato rm elimina las entradas para un archivo, grupo de archivos o archivos seleccionados determinados que se han especificado de una lista de un directorio. ', 'https://www.ionos.es/digitalguide/servidores/configuracion/comando-rm-de-linux/', 'https://i.ibb.co/kHDjyM2/rm.png', 'rm archivo.txt\r\nrm archivo1.txt archivo2.txt archivo3.txt\r\nrm -r directorio/\r\nrm -rf directorio forzado/\r\n');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `linux_commands`
--
ALTER TABLE `linux_commands`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `linux_commands`
--
ALTER TABLE `linux_commands`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=63;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
